# Generated by Django 4.2.4 on 2023-09-19 05:08

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='게시글 제목')),
                ('content', models.TextField(verbose_name='게시글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to=articles.models.rename_imagefile_to_uuid, verbose_name='업로드이미지')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
